# copyright 2018 CERN for the benefit of the LHCb collaboration (see LICENSE)

language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y git
    - pip install flake8 python_dateutil
script:
    - flake8 overleaf_comment.py
    - nose2
